name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts rpm fakeroot dpkg-dev
      
      - name: Extract version
        id: version
        run: |
          VERSION=$(grep 'VERSION =' Makefile | cut -d'=' -f2 | tr -d ' ')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build Debian package
        run: |
          mkdir -p dist
          chmod +x packaging/build-deb.sh
          packaging/build-deb.sh
      
      - name: Build RPM package
        run: |
          chmod +x packaging/build-rpm.sh
          packaging/build-rpm.sh
      
      - name: Create tarball
        run: |
          VERSION=$(grep 'VERSION =' Makefile | cut -d'=' -f2 | tr -d ' ')
          BUILD_DIR="/tmp/i3-gnome-tarball"
          mkdir -p "$BUILD_DIR"
          cp -r ./* "$BUILD_DIR"
          rm -rf "$BUILD_DIR/.git" "$BUILD_DIR/dist"
          tar -czf "dist/i3-gnome-$VERSION.tar.gz" -C "$(dirname $BUILD_DIR)" "$(basename $BUILD_DIR)"
      
      - name: Build binary package
        run: |
          chmod +x packaging/build-binary.sh
          packaging/build-binary.sh
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: dist/
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: i3-gnome ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.run
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  publish-packages:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: packages
          path: dist
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract version
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: packaging/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/i3-gnome:latest
            ghcr.io/${{ github.repository_owner }}/i3-gnome:${{ env.VERSION }} 