name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential debhelper devscripts rpm
      
      - name: Extract version
        id: version
        run: |
          VERSION=$(grep 'VERSION =' Makefile | cut -d'=' -f2 | tr -d ' ')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      
      - name: Build Debian package
        run: |
          mkdir -p dist
          chmod +x packaging/build-deb.sh
          packaging/build-deb.sh
      
      - name: Build RPM package
        run: |
          chmod +x packaging/build-rpm.sh
          packaging/build-rpm.sh
      
      - name: Create tarball
        run: |
          VERSION=$(grep 'VERSION =' Makefile | cut -d'=' -f2 | tr -d ' ')
          BUILD_DIR="/tmp/i3-gnome-tarball"
          mkdir -p "$BUILD_DIR"
          cp -r ./* "$BUILD_DIR"
          rm -rf "$BUILD_DIR/.git" "$BUILD_DIR/dist"
          tar -czf "dist/i3-gnome-$VERSION.tar.gz" -C "$(dirname $BUILD_DIR)" "$(basename $BUILD_DIR)"
      
      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          name: i3-gnome ${{ steps.version.outputs.version }}
          draft: false
          prerelease: false
          files: |
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 